change from auto merge to auto approve
Unfortunately, enabling auto merge does not work for dependabot:

    Message: ["Pull request User is not authorized for this protected branch"], Locations: [{Line:1 Column:72}]
    8
    Error: Process completed with exit code 1.